# Generated by Django 4.0.6 on 2023-01-24 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='item_image',
            field=models.CharField(default='https://thumbs.dreamstime.com/b/add-photo-line-icon-image-thumbnail-sign-picture-placeholder-symbol-quality-design-element-linear-style-editable-stroke-vector-219079541.jpg', max_length=500),
        ),
    ]
